# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [5]:
import numpy as np


#### 2. Print the numpy version and the configuration  (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
nullvector = np.zeros(10)
print(nullvector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
n = np.zeros((3,3))
print("%d bytes" % (n.size * n.itemsize))

72 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
nullv = np.zeros(10)
print(nullv)
print("Update fifth value to 1")
nullv[6] = 1
print(nullv)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update fifth value to 1
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
f = np.arange(10, 50, 1)
print(f)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [11]:
f = np.arange(50)
f = f[::-1]
print(f)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
f = np.arange(9).reshape(3,3)
print(f)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [13]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [14]:
f = np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
f = np.random.random((3,3,3))
print(f)

[[[0.12289657 0.56041234 0.00571458]
  [0.07748685 0.01571017 0.25989424]
  [0.74355962 0.17051209 0.14286357]]

 [[0.33196935 0.52549989 0.22902868]
  [0.1684038  0.90353754 0.20678201]
  [0.40009975 0.09363673 0.39856591]]

 [[0.20822721 0.73884771 0.83294713]
  [0.94362529 0.6269719  0.39650606]
  [0.18991761 0.60610496 0.86165994]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [19]:
f = np.random.random((10,10))
fmin,fmax=f.min(),f.max()
print(fmin,fmax)


0.0006573718759491642 0.9938414922054791


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
f = np.random.random((30))
print(f)
print(f.mean())

[0.71159081 0.60209719 0.10864076 0.1611651  0.27354221 0.46267504
 0.17291923 0.5415659  0.32711301 0.42848348 0.88963518 0.16768427
 0.93188944 0.69984869 0.91877848 0.29119445 0.16168165 0.63040452
 0.72965569 0.81411411 0.09416719 0.27169128 0.25581859 0.71889063
 0.98625007 0.71057371 0.43425972 0.48536178 0.02202091 0.33653535]
0.47800828206379997


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [23]:
f = np.full((4, 4), 1, dtype = 'complex')
f[1:-1,1:-1]=0
print(f)

[[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j 0.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j 1.+0.j]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [27]:
f = np.full((4, 4), 2, dtype = 'complex')
f = np.pad(f, pad_width=1, mode='constant', constant_values=0)
print(f)

[[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 0.+0.j]
 [0.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 0.+0.j]
 [0.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 0.+0.j]
 [0.+0.j 2.+0.j 2.+0.j 2.+0.j 2.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [28]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [29]:
f = np.diag(1+np.arange(4),k=-1)
print(f)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [30]:
f = np.zeros((8,8),dtype=int)
f[1::2,::2] = 1
f[::2,1::2] = 1
print(f)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [32]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [31]:
f = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(f)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [35]:
Z = np.random.random((5,5))
print(Z)
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[0.93659026 0.3423801  0.27933008 0.97279432 0.25733322]
 [0.10056939 0.12199546 0.23910909 0.80808113 0.75060023]
 [0.79030898 0.34637059 0.8343268  0.04359593 0.73996451]
 [0.05358451 0.15148812 0.28964579 0.53189437 0.05728643]
 [0.2646223  0.30437309 0.93585758 0.72463864 0.59101111]]
[[ 1.53529803 -0.37373634 -0.57629878  1.65161175 -0.64696866]
 [-1.15060787 -1.08177177 -0.70551778  1.1224334   0.93776302]
 [ 1.06533637 -0.36091599  1.20675354 -1.33364799  0.90359339]
 [-1.30155742 -0.98701994 -0.54315722  0.23512105 -1.28966416]
 [-0.62355082 -0.49584245  1.53294412  0.85435557  0.42504693]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [37]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [38]:
f = np.dot(np.ones((5,3)), np.ones((3,2)))
print(f)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [6]:
Z = np.arange(11)
print(Z)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [7]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [88]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in power
  """Entry point for launching an IPython kernel.


TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [87]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [86]:

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[  5.   7.   5.  -8.  -7.  -5.  -9.   7. -10.  -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [85]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 4 5 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [84]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [83]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [82]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yesterday
today
tomorrow

numpy.datetime64('2019-10-31')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [78]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [77]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [76]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[8. 9. 1. 1. 1. 3. 4. 6. 3. 1.]
[8. 9. 1. 1. 1. 3. 4. 6. 3. 1.]
[8. 9. 1. 1. 1. 3. 4. 6. 3. 1.]
[8 9 1 1 1 3 4 6 3 1]
[8. 9. 1. 1. 1. 3. 4. 6. 3. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [75]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [74]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [73]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [72]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.04447342 0.12330682 0.22981632 0.23253296 0.36464933 0.54011097
 0.55609744 0.598613   0.65510061 0.83833169]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [71]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [70]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [69]:
Z = np.zeros(10)
Z.flags.writeable = False
#Z[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [67]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.09151902 0.90806489 0.61839802 1.12193049 0.28343275 0.83664676
 0.67131576 0.52739177 1.0554745  0.57053891]
[0.90070081 1.12627147 1.24551249 0.89462573 0.31051755 0.52720157
 1.56524423 0.12403207 0.47562046 0.30181371]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [66]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.41057697 0.18245032 0.86553997 0.40105459 0.10585437 0.
 0.01375147 0.78564288 0.84156728 0.81197381]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [65]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [64]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [63]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [62]:
np.set_printoptions()
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [61]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

81


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [60]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [59]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.41278237 0.67378956 0.29957295 0.64020029 0.660309
  0.76297692 0.76563729 0.54023462 0.64936691]
 [0.41278237 0.         0.66710233 0.11398335 0.7075515  0.6657679
  0.53322594 0.83944918 0.24703939 0.27166868]
 [0.67378956 0.66710233 0.         0.63186678 0.12091345 0.02110866
  0.37234047 0.19878739 0.48343561 0.90264305]
 [0.29957295 0.11398335 0.63186678 0.         0.65388389 0.62705612
  0.56639486 0.78807241 0.29205689 0.3732507 ]
 [0.64020029 0.7075515  0.12091345 0.65388389 0.         0.10122403
  0.48635783 0.13441136 0.55616405 0.95952271]
 [0.660309   0.6657679  0.02110866 0.62705612 0.10122403 0.
  0.38838257 0.18932967 0.48833182 0.90490218]
 [0.76297692 0.53322594 0.37234047 0.56639486 0.48635783 0.38838257
  0.         0.56398923 0.2861985  0.67920322]
 [0.76563729 0.83944918 0.19878739 0.78807241 0.13441136 0.18932967
  0.56398923 0.         0.6759129  1.08737841]
 [0.54023462 0.24703939 0.48343561 0.29205689 0.55616405 0.48833182
  0.2861985  0.6759129 

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [58]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [57]:
from io import StringIO
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [55]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [54]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [53]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [51]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.21321114 -0.60844338  0.33511738  0.30369936 -0.61926552 -0.5260263
   0.30151353  0.17579488  0.2855999   0.13879902]
 [-0.00870406  0.43769059 -0.07236567  0.10724516  0.08809415  0.07390808
   0.06781927 -0.26566248 -0.17956409 -0.24846093]
 [-0.25669906  0.1365015  -0.51345149 -0.3168156   0.29494485 -0.19285428
   0.11326441  0.42926016  0.37786666 -0.07201715]
 [ 0.29595797  0.22753718  0.36085606 -0.40894057  0.16490814  0.17354116
   0.11503065 -0.12763547 -0.44007446 -0.36118067]
 [ 0.36138396  0.32671632  0.29472049 -0.43113752 -0.14963999  0.10589372
  -0.20900047 -0.26720592  0.19913629 -0.23086689]]


#### 59. How to sort an array by the nth column? (★★☆)

In [52]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 5 0]
 [2 5 2]
 [3 8 9]]
[[5 5 0]
 [2 5 2]
 [3 8 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [50]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [49]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.42927220864115856


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [48]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [47]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [46]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[3. 2. 3. 1. 3. 5. 1. 5. 2. 5.]
[5. 3. 5. 1. 5. 9. 1. 9. 3. 9.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [45]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [44]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [43]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[45 67 53 44]
 [53 54 68 36]
 [71 62 70 42]]
[[45 67 53 44]
 [53 54 68 36]
 [71 62 70 42]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [42]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.6731128  0.47299517 0.3234852  0.42978577 0.58283349 0.43129971
 0.45495833 0.3650366  0.70937437 0.47609424]
0    0.673113
1    0.472995
2    0.323485
3    0.429786
4    0.582833
5    0.431300
6    0.454958
7    0.365037
8    0.709374
9    0.476094
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [41]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([2.21233471, 1.98438598, 1.21489352, 1.19416079, 0.77041894])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [40]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [39]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [38]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [37]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 26) ( 0, 36) ( 2, 18) ( 2, 21) ( 2, 48) ( 2, 72) ( 7, 30) ( 7, 58)
 (10, 45) (10, 47) (14, 52) (14, 63) (16, 26) (16, 81) (18, 48) (21, 72)
 (25, 26) (25, 31) (25, 33) (25, 85) (26, 31) (26, 36) (26, 81) (30, 58)
 (33, 85) (36, 69) (36, 90) (45, 47) (52, 63) (69, 90)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [36]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [35]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [34]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [33]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.63491419, -0.82631766, -0.57852573,  0.6917644 , -0.41838368,
        0.55726074,  0.55273763,  0.18200887, -0.23370188,  0.27660529,
        0.2155087 , -0.72307752, -0.50222328,  0.91405816, -0.0402416 ,
       -0.05871036,  0.63697181,  0.01638289, -0.37960678,  0.45763813,
        0.58251417, -0.19963807, -0.4114236 , -0.38601484,  0.25843032,
        0.09006615,  0.33692967, -0.12675824,  0.18619604,  0.86650953,
       -0.03184763,  0.28864734, -0.00365749, -0.27404193,  0.50597855,
       -0.6889846 ,  0.6520733 , -0.28277768, -0.68423928, -0.50173971,
        0.94717393,  0.55557191,  0.70791607, -0.58836911, -0.30416868,
       -0.24604633,  0.35399703, -0.88168035, -0.02341028,  0.87371273,
       -0.92721286, -0.96707657, -0.06895099, -0.07546609, -0.20632888,
        0.23795522,  0.33783936, -0.05419156,  0.22865252,  0.21119199,
        0.07859218,  0.58055247,  0.98792634,  0.69601682, -0.46705538,
       -0.26610908, -0.78279512, -0.18312659,  0.43738077, -0.69

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [31]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 3.67468603 11.32634281  7.7148215   8.41719122  1.33341162  0.52818988
  2.06883882  1.40470997  2.04715183 16.13373984]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [32]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.99188195  6.25890018  5.01726287 12.70683921  3.89259491  4.23369539
   6.59302527  6.52123057 10.31538183  7.21464118]
 [11.06963069  8.57491519  2.97287408  6.54627826  4.2531119   4.90993806
  10.09465556 15.97200046  0.18731229  2.92793413]
 [11.22338993  8.03232921  3.39567802  6.03605424  3.67932637  4.33970907
   9.58217886 15.84024205  0.06331523  2.98824048]
 [ 5.50404789  1.70269626  6.79959966 12.01891572  2.82379041  2.70031068
   1.99825586  2.65931277 17.18547191 14.80945481]
 [ 8.63259668  3.55107265  3.36474498  4.82114864  0.30838054  0.26235927
   4.87694415 11.55517901  2.87232328  0.25423085]
 [13.71092127  2.39664482  8.59978484  0.04476253  2.45369124  1.7289164
   4.36824922 15.20906758  2.10872056  4.47738928]
 [15.08107136  4.48668045  8.76187039  0.48568564  0.62533164  0.14624065
   6.58255788 17.34159246  3.5794884   6.14644256]
 [ 7.18617036  8.87874937  8.51648253  3.00743231 12.48608698 11.98704955
   7.47143563  4.42235586  4.96504284  3.68687744]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [29]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[1 4 7 5 3 3 1 5 3 6]
 [6 0 1 7 5 6 9 4 9 7]
 [8 0 9 5 8 7 3 3 0 1]
 [8 1 3 2 7 8 1 3 0 7]
 [4 2 7 3 3 7 9 7 5 0]
 [9 1 6 0 4 0 2 7 4 1]
 [0 0 0 9 7 4 5 9 6 7]
 [8 2 8 8 6 9 7 4 4 0]
 [3 2 0 2 3 3 9 3 4 9]
 [9 3 6 4 5 1 0 7 0 2]]
[[0 0 0 0 0]
 [0 1 4 7 5]
 [0 6 0 1 7]
 [0 8 0 9 5]
 [0 8 1 3 2]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [89]:

from numpy.lib import stride_tricks
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [27]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [26]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [90]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 4 0]
   [0 4 4]
   [0 4 2]]

  [[4 0 1]
   [4 4 3]
   [4 2 4]]

  [[0 1 2]
   [4 3 2]
   [2 4 1]]

  [[1 2 0]
   [3 2 4]
   [4 1 1]]

  [[2 0 2]
   [2 4 4]
   [1 1 0]]

  [[0 2 4]
   [4 4 2]
   [1 0 4]]

  [[2 4 4]
   [4 2 4]
   [0 4 3]]

  [[4 4 1]
   [2 4 1]
   [4 3 4]]]


 [[[0 4 4]
   [0 4 2]
   [0 2 4]]

  [[4 4 3]
   [4 2 4]
   [2 4 0]]

  [[4 3 2]
   [2 4 1]
   [4 0 1]]

  [[3 2 4]
   [4 1 1]
   [0 1 0]]

  [[2 4 4]
   [1 1 0]
   [1 0 2]]

  [[4 4 2]
   [1 0 4]
   [0 2 0]]

  [[4 2 4]
   [0 4 3]
   [2 0 2]]

  [[2 4 1]
   [4 3 4]
   [0 2 3]]]


 [[[0 4 2]
   [0 2 4]
   [1 0 1]]

  [[4 2 4]
   [2 4 0]
   [0 1 2]]

  [[2 4 1]
   [4 0 1]
   [1 2 0]]

  [[4 1 1]
   [0 1 0]
   [2 0 0]]

  [[1 1 0]
   [1 0 2]
   [0 0 4]]

  [[1 0 4]
   [0 2 0]
   [0 4 2]]

  [[0 4 3]
   [2 0 2]
   [4 2 3]]

  [[4 3 4]
   [0 2 3]
   [2 3 3]]]


 [[[0 2 4]
   [1 0 1]
   [2 0 4]]

  [[2 4 0]
   [0 1 2]
   [0 4 0]]

  [[4 0 1]
   [1 2 0]
   [4 0 0]]

  [[0 1 0]
   [2 0 0]
   [0 0 3]]

  [[1 0 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [24]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7  9  5  7  8]
 [ 9  7  4 15 10]
 [ 5  4  6 42 11]
 [ 7 15 42  1  7]
 [ 8 10 11  7  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [22]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [23]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [21]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [20]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [19]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [18]:
x = np.random.rand(5)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.31 µs ± 246 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.59 µs ± 83.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
3.32 µs ± 404 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [14]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [13]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 4 0]
 [3 0 1]
 [1 2 2]
 [4 4 2]
 [0 0 3]
 [1 2 0]
 [2 4 0]
 [2 4 0]
 [0 2 1]
 [2 4 0]]
[[1 4 0]
 [3 0 1]
 [1 2 2]
 [4 4 2]
 [0 0 3]
 [1 2 0]
 [2 4 0]
 [2 4 0]
 [0 2 1]
 [2 4 0]]
[[1 4 0]
 [3 0 1]
 [1 2 2]
 [4 4 2]
 [0 0 3]
 [1 2 0]
 [2 4 0]
 [2 4 0]
 [0 2 1]
 [2 4 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [12]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])


I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [11]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [10]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.13551567, 0.15715033, 0.22663539, 0.04682925, 0.22897582,
        0.23189409, 0.11058492, 0.11450205, 0.09960898, 0.05424619],
       [0.30730223, 0.3563621 , 0.51392994, 0.10619239, 0.51923721,
        0.52585484, 0.25076799, 0.25965068, 0.2258784 , 0.12301142],
       [0.08948952, 0.10377624, 0.14966159, 0.0309243 , 0.15120712,
        0.15313424, 0.07302617, 0.0756129 , 0.06577807, 0.03582217],
       [0.20742465, 0.24053936, 0.34689542, 0.07167836, 0.35047776,
        0.35494456, 0.16926484, 0.17526053, 0.15246472, 0.08303097],
       [0.27404089, 0.31779068, 0.45830392, 0.09469849, 0.46303675,
        0.4689381 , 0.22362572, 0.23154698, 0.20143009, 0.10969709],
       [0.42806303, 0.49640199, 0.71588939, 0.1479229 , 0.72328226,
        0.73250042, 0.34931249, 0.36168581, 0.31464201, 0.17135132],
       [0.16532322, 0.19171657, 0.27648531, 0.05712965, 0.27934053,
        0.2829007 , 0.13490879, 0.13968752, 0.12151863, 0.06617799],
       [0.36871052, 0.42757403, 0.6166286

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [9]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)
r_int
x_int
y_int

array([ 0.00000000e+00,  1.74026724e+00,  9.81816584e-01, -1.34251287e+00,
       -3.53191891e+00, -4.70449474e+00, -4.59573427e+00, -3.33831870e+00,
       -1.28956083e+00,  1.14234685e+00,  3.55645601e+00,  5.62188218e+00,
        7.09389488e+00,  7.82951803e+00,  7.78700678e+00,  6.99685666e+00,
        5.55535240e+00,  3.60417006e+00,  1.30506373e+00, -1.15819722e+00,
       -3.61328132e+00, -5.89130465e+00, -7.87065053e+00, -9.41689057e+00,
       -1.04714836e+01, -1.09903787e+01, -1.09354306e+01, -1.03330912e+01,
       -9.22690166e+00, -7.67489830e+00, -5.75257980e+00, -3.54832201e+00,
       -1.15854355e+00,  1.31709956e+00,  3.78023622e+00,  6.13780326e+00,
        8.30540149e+00,  1.02098724e+01,  1.17910419e+01,  1.29972950e+01,
        1.37774249e+01,  1.41319792e+01,  1.40585758e+01,  1.35636816e+01,
        1.26345244e+01,  1.13409083e+01,  9.72216360e+00,  7.79464305e+00,
        5.64544223e+00,  3.32503222e+00,  8.88107041e-01, -1.59329248e+00,
       -4.05992507e+00, -

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [7]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [6]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.18755608  0.20510308]
